apiVersion: v1
kind: Service
metadata:
  name: nagiosgen-service
  labels:
    app: nagiosgen
spec:
  type: NodePort
  selector:
    app: nagiosgen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500
